name: daily

permissions:
  contents: write

on:
  schedule:
    - cron: '0 12 * * *' # every day, on 12:00
  workflow_dispatch:

jobs:
    spider:
        runs-on: ubuntu-latest
        environment: keys
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.11.x"
            - run: python3 -m pip install -r requirements.txt
            - run: python3 main.py > daily_log
              env:
                fudan_username: ${{ secrets.FUDAN_USERNAME }}
                fudan_password: ${{ secrets.FUDAN_PASSWORD }}
                bark_token: ${{ secrets.BARK_TOKEN }}
            - name: Commit files 
              id: commit-files
              run: |
                if [ -n "$(git status --porcelain database.json)" ]; then
                    git config --local user.email "github-actions[bot]@users.noreply.github.com"
                    git config --local user.name "github-actions[bot]"
                    git add .
                    git commit -m "daily update"
                    echo "hasChange=true" >> $GITHUB_OUTPUT
                else
                    echo "No changes detected"
                fi
            - name: Push changes
              uses: ad-m/github-push-action@master
              if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}