name: daily

permissions:
  contents: write

on:
  schedule:
    - cron: '0 12 * * *' # every day, on 12:00
  workflow_dispatch:

jobs:
    spider:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.11.x"
            - run: python3 -m pip install -r requirements.txt
            - run: python3 main.py